#apiVersion: environment.btp.sap.crossplane.io/v1alpha1
#kind: CloudFoundryEnvironment
#metadata:
#  name: fc-env
#  namespace: default
#spec:
#  forProvider:
#    cloudManagementRef:
#      name: cis-local
#    initialOrgManagers:
#      - username: <EMAIL>
#        origin: sap.ids  # optional, defaults to sap.ids
#    landscape: cf-eu10
#  SubaccountRef:
#    name: test-123455
